---
- name: Check for current node version
  shell: ". {{ nvm_path }}/nvm.sh && nvm use {{ default_node_version }} > /dev/null 2>&1 && node -v"
  register: current_node_version
  ignore_errors: yes
  changed_when: false

- name: Install node
  command: "source {{ nvm_path }}/nvm.sh && nvm install {{ default_node_version }}"
  args:
    executable: /bin/bash
  when: current_node_version.stdout.find(default_node_version) == -1


- name: Set default node version to installed node
  command: "source {{ nvm_path }}/nvm.sh && nvm alias default {{ default_node_version }}"
  args:
    executable: /bin/bash
  when: current_node_version.stdout.find(default_node_version) == -1
