---
- name: Install node
  command: ". {{ nvm_path }}/nvm.sh && nvm install {{ default_node_version }}"

- name: Set default node version to installed node
  command: ". {{ nvm_path }}/nvm.sh && nvm alias default {{ node_version }}"
