---
- name: Install dependencies
  action: "{{ ansible_pkg_mgr }} name={{ item }} state=present"
  with_items: "{{ nvm_dependencies[ansible_pkg_mgr] }}"

- name: Check for nvm
  stat:
    path: "{{ nvm_path }}"
  register: nvm_installed_path

- name: Install nvm
  git:
    repo: https://github.com/creationix/nvm.git
    dest: "{{ nvm_path }}"
    version: "{{ nvm_version }}"
    accept_hostkey: true
  when: not nvm_installed_path.stat.exists

- name: Source nvm
  lineinfile:
    dest: "{{ nvm_profile_file }}"
    line: "source {{ nvm_path }}/nvm.sh"

- name: Install nodes
  shell: ". {{ nvm_path }}/nvm.sh && nvm install {{ item }}"
  with_items: "{{ node_versions }}"
